### ISSUE TITLE
lfetool download command isn't exist

### ISSUE THREAD

**Issue by harlanasimov** [lfex/ledis#5]
some error when run make compile:
Getting dependencies ...

Unknown command: 'download'

Script: lfetool, v

Usage: /usr/local/bin/lfetool <command> <context> [<arg> | <context command> <arg>] | <options>

Currently, lfetool supports these commands (with subcommands nested):
- help
- version
- extract
- install
  - lfetool (or no parameter/empty string), autocomplete, lfe, erlang,
    erjang, kerl, relx, rebar, expm
- update
  - lfetool (or no parameter/empty string), deps
- new
  - script, library, service, presentation
  - yaws
    - default (or no parameter/empty string), bootstrap
- tests
  - build, unit, integration, system, all, clean
- repl
  - lfe (or no parameter/empty string), erlang, jlfe, jerl
- info
  - bindir, erllibs, path, installdir, version

Additionally, instead of passing a command, you may choose to run the script
with one of the following options:
 -h    display this usage message and exit
 -v    display the version number and exit

If you are running the compressed lfetool, the following options are also
available:
 -x    extract the compressed lfetool source and use that instead of
       the wrapper

These commands are documented on the project page here:
  https://github.com/lfe/lfetool

Example:
  lfetool install lfetool /usr/local/bin
  lfetool new library my-first-project
  lfetool new service my-otp-app1
  lfetool new yaws default my-yasw-app1
make: **\* [get-deps] Error 1

**Comment by oubiwann** [comment]
Ah, thanks for this -- I need to update this project to use rebar3. I will probably get to this today sometime, so you shouldn't have to wait too long!

**Comment by oubiwann** [comment]
This has been fixed, and `lfetool` is no longer a dependency. That was designed for a much older LFE (versions prior to v.0.8.0). The latest versions of LFE have much of the important bits in LFE tool, and many of the remaining important bits are now either part of rebar3 or are provided by LFE rebar3 plugins. (Though some of the things still missing are third-party tool installation, e.g., kerl, and skeleton project generation from template files).

Let me know how the latest works for you ...

**Comment by oubiwann** [comment]
Done.
